BALANCE_SHEET_ACCOUNTS = [
    ("311001", "Buildings Cost", "ASSETS", "FIXED_ASSET", False, ""),
    ("311002", "Office Equipment Cost", "ASSETS", "FIXED_ASSET", False, ""),
    ("311003", "Furniture & Fittings Cost", "ASSETS", "FIXED_ASSET", False, ""),
    ("311004", "Motor Vehicles Cost", "ASSETS", "FIXED_ASSET", False, ""),
    ("311005", "Vehicles Cost", "ASSETS", "FIXED_ASSET", False, ""),
    ("311006", "Software Cost", "ASSETS", "FIXED_ASSET", False, ""),
    ("311007", "Computer Equipment Cost", "ASSETS", "FIXED_ASSET", False, ""),
    ("311008", "Farm Equipment Cost", "ASSETS", "FIXED_ASSET", False, ""),
    ("312001", "Accumulated Depreciation - Buildings", "ASSETS", "ACCUMULATED_DEPRECIATION", False, "NEW"),
    ("312002", "Accumulated Depreciation - Office Equipment", "ASSETS", "ACCUMULATED_DEPRECIATION", False, "NEW"),
    ("312003", "Accumulated Depreciation - Furniture & Fittings", "ASSETS", "ACCUMULATED_DEPRECIATION", False, "NEW"),
    ("312004", "Accumulated Depreciation - Motor Vehicles", "ASSETS", "ACCUMULATED_DEPRECIATION", False, "NEW"),
    ("312005", "Accumulated Depreciation - Vehicles", "ASSETS", "ACCUMULATED_DEPRECIATION", False, "NEW"),
    ("312006", "Accumulated Amortisation - Software", "ASSETS", "ACCUMULATED_DEPRECIATION", False, "NEW"),
    ("312007", "Accumulated Depreciation - Computer Equipment", "ASSETS", "ACCUMULATED_DEPRECIATION", False, "NEW"),
    ("312008", "Accumulated Depreciation - Farm Equipment", "ASSETS", "ACCUMULATED_DEPRECIATION", False, "NEW"),
    ("321001", "Inventory Purchases", "ASSETS", "CURRENT_ASSET", False, ""),
    ("321002", "Inventories (Laying Birds)", "ASSETS", "CURRENT_ASSET", False, ""),
    ("321003", "Inventories (Breeder Rabbits)", "ASSETS", "CURRENT_ASSET", False, ""),
    ("321004", "Inventories_(Breeder Goats)", "ASSETS", "CURRENT_ASSET", False, ""),
    ("321005", "Investments", "ASSETS", "CURRENT_ASSET", False, "MOVED"),
    ("321006", "Misc. Expenses (Asset)", "ASSETS", "CURRENT_ASSET", False, "MOVED"),
    ("331001", "Trade Debtors", "ASSETS", "RECEIVABLE", True, ""),
    ("331002", "Other Receivables", "ASSETS", "RECEIVABLE", True, ""),
    ("331003", "Staff Advances", "ASSETS", "RECEIVABLE", True, "MOVED"),
    ("331004", "WHT Receivable", "ASSETS", "RECEIVABLE", True, "NEW"),
    ("331005", "VAT Input Receivable", "ASSETS", "RECEIVABLE", True, "MOVED"),
    ("341001", "Prepaid Electricity", "ASSETS", "PREPAYMENT", True, ""),
    ("341002", "Prepaid Salaries", "ASSETS", "PREPAYMENT", True, ""),
    ("341003", "Prepaid Rent", "ASSETS", "PREPAYMENT", True, ""),
    ("341004", "Prepaid Water", "ASSETS", "PREPAYMENT", True, "NEW"),
    ("351001", "Fixed Deposit Account", "ASSETS", "BANK_AND_CASH", False, ""),
    ("351002", "Centenary Bank UGX Account (Sales)", "ASSETS", "BANK_AND_CASH", False, ""),
    ("351003", "Centenary Bank UGX Account (Operations)", "ASSETS", "BANK_AND_CASH", False, ""),
    ("351004", "Centenary Bank UGX Account (Garden)", "ASSETS", "BANK_AND_CASH", False, ""),
    ("351005", "MTN Mobile Money UGX Account", "ASSETS", "BANK_AND_CASH", False, ""),
    ("351006", "Airtel Mobile Money UGX Account", "ASSETS", "BANK_AND_CASH", False, ""),
    ("351007", "Reconciliation Account", "ASSETS", "BANK_AND_CASH", False, ""),
    ("351008", "Cash", "ASSETS", "BANK_AND_CASH", False, ""),
    ("351009", "Petty cash SHS", "ASSETS", "BANK_AND_CASH", False, ""),
    ("351010", "Petty Cash USD", "ASSETS", "BANK_AND_CASH", False, ""),
    ("411001", "Defered_Tax", "LIABILITIES", "NON_CURRENT_LIABILITY", False, ""),
    ("411002", "Loans (Non-Current Portion)", "LIABILITIES", "NON_CURRENT_LIABILITY", False, "RENAMED"),
    ("411003", "Un Earned Contribution", "LIABILITIES", "NON_CURRENT_LIABILITY", False, ""),
    ("411004", "Lease liability", "LIABILITIES", "NON_CURRENT_LIABILITY", False, ""),
    ("421001", "Accrual_and_other_accounts_payable", "LIABILITIES", "CURRENT_LIABILITY", True, ""),
    ("421003", "Corporation_Tax_Payable", "LIABILITIES", "CURRENT_LIABILITY", True, ""),
    ("421005", "Loans (Current Portion)", "LIABILITIES", "CURRENT_LIABILITY", False, "RENAMED"),
    ("421007", "Audit_Fees_Payable", "LIABILITIES", "CURRENT_LIABILITY", True, ""),
    ("421008", "Asset_Disposal_Account", "LIABILITIES", "CURRENT_LIABILITY", True, ""),
    ("421009", "Suspense_Receipts_ugx", "LIABILITIES", "CURRENT_LIABILITY", True, ""),
    ("421010", "Salaries_payable", "LIABILITIES", "CURRENT_LIABILITY", True, ""),
    ("421011", "Duties_&_taxes", "LIABILITIES", "CURRENT_LIABILITY", True, ""),
    ("421012", "PAYE_payable", "LIABILITIES", "CURRENT_LIABILITY", True, ""),
    ("421014", "VAT_standard_rated_18% (Output VAT)", "LIABILITIES", "CURRENT_LIABILITY", True, ""),
    ("421015", "WHT_Payable", "LIABILITIES", "CURRENT_LIABILITY", True, ""),
    ("421016", "NSSF_Payable", "LIABILITIES", "CURRENT_LIABILITY", True, "NEW"),
    ("431001", "Trade Creditors", "LIABILITIES", "PAYABLE", True, ""),
    ("431002", "Other Payables", "LIABILITIES", "PAYABLE", True, ""),
    ("511001", "Share Capital", "EQUITY", "EQUITY", False, ""),
    ("511002", "Revenue Reserves", "EQUITY", "EQUITY", False, ""),
    ("511003", "Retained Earnings", "EQUITY", "EQUITY", False, ""),
    ("511004", "Fixed Asset Reserves", "EQUITY", "EQUITY", False, ""),
    ("511005", "Inventory Reserves", "EQUITY", "EQUITY", False, ""),
    ("511006", "Financial Asset Reserves", "EQUITY", "EQUITY", False, ""),
    ("511007", "Accumulated Reserves", "EQUITY", "EQUITY", False, ""),
    ("521001", "Revenue Reserves", "EQUITY", "CURRENT_YEAR_EARNINGS", False, ""),
]
