# Generated by Django 6.0.3 on 2026-06-19 09:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poultry', '0014_cleaning_evidence_audio_and_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('expense_type', models.CharField(choices=[('COST_OF_REVENUE', 'Cost of Revenue'), ('DEPRECIATION', 'Depreciation'), ('MONTHLY_EXPENSES', 'Monthly Expenses')], db_index=True, default='MONTHLY_EXPENSES', help_text='Categorize expense: Cost of Revenue, Depreciation, or Monthly Expenses', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseTransaction',
            fields=[
                ('expense_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('expense_date', models.DateField(db_index=True)),
                ('description', models.CharField(max_length=255)),
                ('reference_no', models.CharField(blank=True, db_index=True, max_length=80)),
                ('item_name', models.CharField(blank=True, max_length=120)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('supplier_name', models.CharField(blank=True, max_length=150)),
                ('supplier_contact', models.CharField(blank=True, max_length=80)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Mobile Money', 'Mobile Money'), ('Bank', 'Bank'), ('Check', 'Check')], default='Cash', max_length=30)),
                ('period_year', models.PositiveSmallIntegerField(db_index=True)),
                ('period_month', models.PositiveSmallIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses_approved', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expense_date', '-expense_id'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseAllocation',
            fields=[
                ('allocation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('DIRECT', 'Direct Amount'), ('PERCENT', 'Percentage'), ('MANUAL', 'Manual Rule')], default='DIRECT', max_length=10)),
                ('percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('rationale', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_allocations', to='poultry.poultrybatch')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='expenses.expensetransaction')),
            ],
        ),
        migrations.AddIndex(
            model_name='expensetransaction',
            index=models.Index(fields=['category', 'expense_date'], name='expenses_ex_categor_9966c7_idx'),
        ),
        migrations.AddIndex(
            model_name='expensetransaction',
            index=models.Index(fields=['status', 'expense_date'], name='expenses_ex_status_dc20b9_idx'),
        ),
        migrations.AddIndex(
            model_name='expensetransaction',
            index=models.Index(fields=['period_year', 'period_month'], name='expenses_ex_period__f40751_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseallocation',
            index=models.Index(fields=['batch'], name='expenses_ex_batch_i_e03e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseallocation',
            index=models.Index(fields=['expense'], name='expenses_ex_expense_77449d_idx'),
        ),
    ]
