# Generated by Django 5.2.11 on 2026-02-28 03:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poultry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('national_id', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='WagePayment',
            fields=[
                ('wage_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('period_year', models.PositiveSmallIntegerField(db_index=True)),
                ('period_month', models.PositiveSmallIntegerField(db_index=True)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wage_payments', to='poultry.poultrybatch')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wages_paid', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wage_payments', to='hr.worker')),
            ],
            options={
                'ordering': ['-payment_date', '-wage_id'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('work_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('OFF', 'Off / Leave')], default='PRESENT', max_length=10)),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_recorded', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='hr.worker')),
            ],
            options={
                'ordering': ['-work_date', '-attendance_id'],
            },
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['status'], name='hr_worker_status_45a8c0_idx'),
        ),
        migrations.AddIndex(
            model_name='wagepayment',
            index=models.Index(fields=['worker', 'payment_date'], name='hr_wagepaym_worker__b53c42_idx'),
        ),
        migrations.AddIndex(
            model_name='wagepayment',
            index=models.Index(fields=['period_year', 'period_month'], name='hr_wagepaym_period__f620c0_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['worker', 'work_date'], name='hr_attendan_worker__2b9a26_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['work_date', 'status'], name='hr_attendan_work_da_fbfb1e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('worker', 'work_date')},
        ),
    ]
