# Generated by Django 6.0.3 on 2026-06-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_welfarerequest_supervisor_submitted'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='welfarerequest',
            new_name='hr_welfarer_worker__542b37_idx',
            old_name='hr_welfare_worker__736ada_idx',
        ),
        migrations.RenameIndex(
            model_name='welfarerequest',
            new_name='hr_welfarer_request_84a30a_idx',
            old_name='hr_welfare_request_6ddfee_idx',
        ),
        migrations.RenameIndex(
            model_name='welfarerequest',
            new_name='hr_welfarer_created_d29d11_idx',
            old_name='hr_welfare_created_e5d51f_idx',
        ),
    ]
