# Generated by Django 5.2.11 on 2026-09-15 19:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from datetime import date
from django.conf import settings
from django.db import migrations, models


def issue_missing_employee_numbers(apps, schema_editor):
    """Preserve legacy IDs while making automatic IDs unique for all rows."""
    StaffProfile = apps.get_model("hr", "StaffProfile")
    year = date.today().year
    prefix = f"EMP-{year}-"
    used = set()
    highest = 0
    profiles = list(StaffProfile.objects.order_by("pk"))

    for profile in profiles:
        value = (profile.employee_number or "").strip()
        if value and value not in used:
            used.add(value)
            if value.startswith(prefix):
                suffix = value[len(prefix):]
                if suffix.isdigit():
                    highest = max(highest, int(suffix))

    for profile in profiles:
        value = (profile.employee_number or "").strip()
        if value and value in used:
            # Keep the first occurrence of a legacy ID.  Later duplicates and
            # blanks receive the new system format before the unique rule is
            # introduced.
            used.remove(value)
            continue
        highest += 1
        new_value = f"{prefix}{highest:05d}"
        while new_value in used:
            highest += 1
            new_value = f"{prefix}{highest:05d}"
        profile.employee_number = new_value
        profile.save(update_fields=["employee_number"])
        used.add(new_value)


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_welfarerequest_advance_period'),
        ('payroll', '0005_staff_hr_and_advance_register'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractRenewal',
            fields=[
                ('renewal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('previous_contract_start_date', models.DateField(blank=True, null=True)),
                ('previous_contract_end_date', models.DateField(blank=True, null=True)),
                ('renewed_contract_start_date', models.DateField()),
                ('renewed_contract_end_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('renewal_document', models.FileField(blank=True, upload_to='staff_contracts/')),
                ('renewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-renewed_contract_end_date', '-renewal_id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('document_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('CONTRACT', 'Employment contract'), ('TAX', 'Tax document'), ('NSSF', 'NSSF document'), ('QUALIFICATION', 'Qualification / certificate'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('document', models.FileField(upload_to='employee_documents/')),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at', '-document_id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryAdvanceAllocation',
            fields=[
                ('allocation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['salary_payment__period_month', 'allocation_id'],
            },
        ),
        migrations.CreateModel(
            name='UnpaidAbsence',
            fields=[
                ('absence_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('absence_date', models.DateField(db_index=True)),
                ('reason', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-absence_date', '-absence_id'],
            },
        ),
        migrations.RenameField(
            model_name='staffprofile',
            old_name='age',
            new_name='legacy_age',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='contract_end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='contract_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='legacy_age',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='lst_local_government',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='pay_basis',
            field=models.CharField(choices=[('MONTHLY', 'Monthly salary'), ('HOURLY', 'Hourly wage')], db_index=True, default='MONTHLY', max_length=10),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='pay_lst',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='welfarerequest',
            name='advance_disbursed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='welfare_advances_disbursed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='welfarerequest',
            name='advance_disbursed_on',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='welfarerequest',
            name='advance_journal_reference',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='welfarerequest',
            name='advance_payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('MOBILE_MONEY', 'Mobile Money'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='welfarerequest',
            name='advance_payment_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.RunPython(issue_missing_employee_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='staffprofile',
            name='employee_number',
            field=models.CharField(blank=True, editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='welfarerequest',
            name='request_type',
            field=models.CharField(choices=[('LEAVE', 'Leave'), ('SALARY_ADVANCE', 'Salary Advance')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['pay_basis', 'employment_status'], name='hr_staffpro_pay_bas_17fd6a_idx'),
        ),
        migrations.AddField(
            model_name='contractrenewal',
            name='renewed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_renewals_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractrenewal',
            name='staff_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_renewals', to='hr.staffprofile'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='staff_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hr.staffprofile'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_documents_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryadvanceallocation',
            name='advance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_advance_allocations', to='hr.welfarerequest'),
        ),
        migrations.AddField(
            model_name='salaryadvanceallocation',
            name='allocated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salary_advance_allocations_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryadvanceallocation',
            name='salary_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_advance_allocations', to='payroll.salarypayment'),
        ),
        migrations.AddField(
            model_name='unpaidabsence',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unpaid_absences_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unpaidabsence',
            name='staff_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unpaid_absences', to='hr.staffprofile'),
        ),
        migrations.AddIndex(
            model_name='contractrenewal',
            index=models.Index(fields=['staff_profile', 'renewed_contract_end_date'], name='hr_contract_staff_p_66649c_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['staff_profile', 'document_type'], name='hr_employee_staff_p_03b13d_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryadvanceallocation',
            index=models.Index(fields=['advance', 'salary_payment'], name='hr_salaryad_advance_3d3867_idx'),
        ),
        migrations.AddConstraint(
            model_name='salaryadvanceallocation',
            constraint=models.UniqueConstraint(fields=('advance', 'salary_payment'), name='hr_one_advance_allocation_per_salary_month'),
        ),
        migrations.AddIndex(
            model_name='unpaidabsence',
            index=models.Index(fields=['staff_profile', 'absence_date'], name='hr_unpaidab_staff_p_73df2a_idx'),
        ),
        migrations.AddConstraint(
            model_name='unpaidabsence',
            constraint=models.UniqueConstraint(fields=('staff_profile', 'absence_date'), name='hr_one_unpaid_absence_per_day'),
        ),
    ]
