# Generated by Django 5.2.11 on 2026-04-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_houses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('WORKER', 'Farm Worker'), ('SUPERVISOR', 'Farm Supervisor'), ('MANAGER', 'Farm Manager'), ('OWNER', 'Business Owner')], max_length=20, unique=True),
        ),
    ]
