# Generated by Codex on 2026-05-29

import decimal
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_role_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestorCapitalTransaction",
            fields=[
                ("transaction_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("STARTUP", "Startup Capital"),
                            ("ADDITION", "Additional Capital"),
                            ("WITHDRAWAL", "Owner Withdrawal"),
                        ],
                        db_index=True,
                        default="ADDITION",
                        max_length=12,
                    ),
                ),
                ("transaction_date", models.DateField(db_index=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(decimal.Decimal("0.00"))],
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investor_capital_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date", "-created_at"],
                "indexes": [
                    models.Index(fields=["transaction_type", "transaction_date"], name="accounts_in_transa_5dc331_idx"),
                ],
            },
        ),
    ]
