# Generated by Codex on 2026-05-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_investorcapitaltransaction"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="investorcapitaltransaction",
            new_name="accounts_in_transac_6942fb_idx",
            old_name="accounts_in_transa_5dc331_idx",
        ),
    ]
