# Generated by Django 6.0.3 on 2026-05-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_seed_sales_item_categories'),
        ('inventory', '0002_supplier'),
    ]

    operations = [
    ]
