# Generated by Django 6.0.3 on 2026-06-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryrequisition'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inventoryrequisition',
            new_name='inventory_i_request_fdd012_idx',
            old_name='inventory_r_request_87a7a3_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryrequisition',
            new_name='inventory_i_status_0b1d2c_idx',
            old_name='inventory_r_status_4696d5_idx',
        ),
    ]
