# Generated by Django 6.0.4 on 2026-05-03 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poultry', '0006_approval_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('SYSTEM', 'System Alert'), ('DIRECT', 'Direct Message'), ('MAINTENANCE', 'Maintenance Task'), ('HEALTH', 'Health Alert'), ('COMPLIANCE', 'Compliance Alert')], max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlertTemplate',
            fields=[
                ('template_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('title_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('frequency_days', models.IntegerField(blank=True, help_text='If set, alert repeats every N days', null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('alert_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alerts.alerttype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlertSchedule',
            fields=[
                ('schedule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('last_alert_sent', models.DateTimeField(blank=True, null=True)),
                ('next_alert_due', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poultry.poultryhouse')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.alerttemplate')),
            ],
            options={
                'ordering': ['next_alert_due'],
                'indexes': [models.Index(fields=['is_active', 'next_alert_due'], name='alerts_aler_is_acti_b87028_idx')],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('UNREAD', 'Unread'), ('READ', 'Read'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='UNREAD', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, help_text='When action should be taken', null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_alerts', to=settings.AUTH_USER_MODEL)),
                ('related_batch', models.ForeignKey(blank=True, help_text='If alert is related to specific batch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='poultry.poultrybatch')),
                ('related_house', models.ForeignKey(blank=True, help_text='If alert is related to specific poultry house', null=True, on_delete=django.db.models.deletion.SET_NULL, to='poultry.poultryhouse')),
                ('sender', models.ForeignKey(blank=True, help_text='Null if system-generated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_alerts', to=settings.AUTH_USER_MODEL)),
                ('alert_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='alerts.alerttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['receiver', '-created_at'], name='alerts_aler_receive_e2d513_idx'), models.Index(fields=['status', 'receiver'], name='alerts_aler_status_95b16a_idx'), models.Index(fields=['priority', '-created_at'], name='alerts_aler_priorit_eb910e_idx')],
            },
        ),
    ]
