# Generated by Django 5.2.11 on 2026-05-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='persist_until_resolved',
            field=models.BooleanField(default=False, help_text='Keep this alert active in reminder counts until it is explicitly resolved.'),
        ),
    ]
