# Generated by Django 6.0.3 on 2026-06-19 09:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('salary_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period_month', models.CharField(db_index=True, max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending')], db_index=True, default='PENDING', max_length=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_payments', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salaries_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_month', 'employee__username'],
            },
        ),
    ]
