# Generated by Django 5.2.11 on 2026-09-15 19:21

import django.core.validators
import django.db.models.deletion
from django.db.models import F
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_salary_statuses(apps, schema_editor):
    """Keep the old two-state payroll history readable in the new workflow."""
    SalaryPayment = apps.get_model("payroll", "SalaryPayment")
    # A historical PENDING record was a prepared, unpaid salary.  It must not
    # be treated as a liability merely because this schema now uses a clearer
    # status name.  Historic PAID rows did not have payment-disbursement rows,
    # so preserve their paid balance explicitly.
    SalaryPayment.objects.filter(status="PENDING").update(
        status="PREPARED",
        payment_date=None,
    )
    SalaryPayment.objects.filter(status="PAID", amount_paid=Decimal("0.00")).update(
        amount_paid=F("amount"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_salarybonus_bonus_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyWorkEntry',
            fields=[
                ('work_entry_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('work_date', models.DateField(db_index=True)),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-work_date', '-work_entry_id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryDisbursement',
            fields=[
                ('disbursement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('MOBILE_MONEY', 'Mobile Money'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], max_length=20)),
                ('payment_reference', models.CharField(help_text='Receipt, bank, mobile-money, or batch reference supplied when the payment is made.', max_length=120)),
                ('paid_on', models.DateField(db_index=True)),
                ('accounting_entry_reference', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-paid_on', '-disbursement_id'],
            },
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total of actual salary disbursements recorded against this payroll line.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Hourly rate snapshot used for this payroll line.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Approved hourly-work total used to calculate this payroll line.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='liability_accrued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='liability_entry_reference',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='lst_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Uganda Local Service Tax deducted for the selected payroll month.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='pay_basis',
            field=models.CharField(choices=[('MONTHLY', 'Monthly salary'), ('HOURLY', 'Hourly wage')], db_index=True, default='MONTHLY', max_length=10),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='status',
            field=models.CharField(choices=[('PREPARED', 'Prepared — unpaid'), ('PART_PAID', 'Part-paid'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled / employee inactive')], db_index=True, default='PREPARED', max_length=10),
        ),
        migrations.AddIndex(
            model_name='salarypayment',
            index=models.Index(fields=['period_month', 'status'], name='payroll_sal_period__34e80e_idx'),
        ),
        migrations.AddField(
            model_name='hourlyworkentry',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hourly_work_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hourlyworkentry',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hourly_work_entries_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hourlyworkentry',
            name='salary_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hourly_work_entries', to='payroll.salarypayment'),
        ),
        migrations.AddField(
            model_name='salarydisbursement',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_disbursements_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salarydisbursement',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='payroll.salarypayment'),
        ),
        migrations.AddIndex(
            model_name='hourlyworkentry',
            index=models.Index(fields=['employee', 'work_date'], name='payroll_hou_employe_517a82_idx'),
        ),
        migrations.AddIndex(
            model_name='hourlyworkentry',
            index=models.Index(fields=['salary_payment', 'work_date'], name='payroll_hou_salary__4ac94e_idx'),
        ),
        migrations.AddIndex(
            model_name='salarydisbursement',
            index=models.Index(fields=['salary', 'paid_on'], name='payroll_sal_salary__911a46_idx'),
        ),
        migrations.AddIndex(
            model_name='salarydisbursement',
            index=models.Index(fields=['payment_reference'], name='payroll_sal_payment_be9957_idx'),
        ),
        migrations.RunPython(migrate_legacy_salary_statuses, migrations.RunPython.noop),
    ]
