# Generated by Django 5.2.11 on 2026-02-19 14:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MortalityCause',
            fields=[
                ('cause_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoultryBatch',
            fields=[
                ('batch_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('batch_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('supplier_name', models.CharField(blank=True, max_length=150)),
                ('date_stocked', models.DateField(db_index=True)),
                ('initial_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('expected_lay_start', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_stocked', '-batch_id'],
            },
        ),
        migrations.CreateModel(
            name='MortalityRecord',
            fields=[
                ('mortality_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('record_date', models.DateField(db_index=True)),
                ('number_dead', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='poultry.mortalitycause')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mortality_reported', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mortality_records', to='poultry.poultrybatch')),
            ],
            options={
                'ordering': ['-record_date', '-mortality_id'],
                'indexes': [models.Index(fields=['batch', 'record_date'], name='poultry_mor_batch_i_298547_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyProduction',
            fields=[
                ('production_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('record_date', models.DateField(db_index=True)),
                ('birds_alive', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('eggs_collected', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('eggs_rejected', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_production_created', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_production', to='poultry.poultrybatch')),
            ],
            options={
                'ordering': ['-record_date', '-production_id'],
                'indexes': [models.Index(fields=['batch', 'record_date'], name='poultry_dai_batch_i_4ca2ce_idx')],
                'unique_together': {('batch', 'record_date')},
            },
        ),
    ]
