# Generated by Django 6.0.3 on 2026-04-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0002_poultryhouse_poultrybatch_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='poultrybatch',
            name='initial_age_days',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
