# Generated by Django 5.2.11 on 2026-04-26 15:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0003_poultrybatch_initial_age_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='egg_collection',
            fields=[
                ('collection_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('collection_date', models.DateField(db_index=True)),
                ('eggs_collected', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('eggs_rejected', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egg_collections', to='poultry.poultrybatch')),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egg_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-collection_date', '-collection_id'],
                'indexes': [models.Index(fields=['batch', 'collection_date'], name='poultry_egg_batch_i_f85429_idx')],
            },
        ),
    ]
