# Generated by Django 5.2.11 on 2026-04-26 15:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0004_egg_collection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningRecord',
            fields=[
                ('cleaning_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('record_date', models.DateField(db_index=True)),
                ('house_cleaned', models.BooleanField(default=False)),
                ('disinfection_done', models.BooleanField(default=False)),
                ('water_changed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cleaning_records', to='poultry.poultrybatch')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cleaning_records_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-record_date', '-cleaning_id'],
                'indexes': [models.Index(fields=['batch', 'record_date'], name='poultry_cle_batch_i_a726ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeedRecord',
            fields=[
                ('feed_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('record_date', models.DateField(db_index=True)),
                ('feed_type', models.CharField(choices=[('STARTER', 'Starter'), ('GROWER', 'Grower'), ('LAYER_MASH', 'Layer Mash'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('time_given', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feed_records', to='poultry.poultrybatch')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feed_records_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-record_date', '-feed_id'],
                'indexes': [models.Index(fields=['batch', 'record_date'], name='poultry_fee_batch_i_076bd5_idx')],
            },
        ),
    ]
