# Generated by Django 6.0.3 on 2026-05-04 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0006_approval_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningPhoto',
            fields=[
                ('photo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='cleaning_photos/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cleaning_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='poultry.cleaningrecord')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cleaning_photos_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
