# Generated by Django 6.0.3 on 2026-05-07 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_treatmentplanitem_duration_days_and_more'),
        ('poultry', '0007_cleaningphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningrecord',
            name='sickness_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sickbay_cleaning_records', to='health.sicknessreport'),
        ),
        migrations.AddField(
            model_name='egg_collection',
            name='sickness_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sickbay_egg_collections', to='health.sicknessreport'),
        ),
        migrations.AddField(
            model_name='feedrecord',
            name='sickness_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sickbay_feed_records', to='health.sicknessreport'),
        ),
        migrations.AddIndex(
            model_name='cleaningrecord',
            index=models.Index(fields=['sickness_report', 'record_date'], name='poultry_cle_sicknes_fae964_idx'),
        ),
        migrations.AddIndex(
            model_name='egg_collection',
            index=models.Index(fields=['sickness_report', 'collection_date'], name='poultry_egg_sicknes_bfe979_idx'),
        ),
        migrations.AddIndex(
            model_name='feedrecord',
            index=models.Index(fields=['sickness_report', 'record_date'], name='poultry_fee_sicknes_26f2a4_idx'),
        ),
    ]
