# Generated by Django 6.0.3 on 2026-05-17 09:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0008_cleaningrecord_sickness_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poultrybatch',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
