# Generated by Django 6.0.3 on 2026-05-18 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0011_feed_mixture_feedrecord_feed_mixture'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='feedmixture',
            new_name='poultry_fee_mix_dat_d489a7_idx',
            old_name='poultry_fee_mix_dat_e17981_idx',
        ),
        migrations.RenameIndex(
            model_name='feedmixture',
            new_name='poultry_fee_mixed_b_891da5_idx',
            old_name='poultry_fee_mixed__8c57f4_idx',
        ),
    ]
