# Generated by Django 5.2.11 on 2026-10-04 11:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0016_investor_kpi_target'),
        ('sales', '0007_receivable_entries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poultrybatch',
            name='origin_batch',
            field=models.ForeignKey(blank=True, help_text='Original stocked batch when this batch was created by a bird transfer.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_descendants', to='poultry.poultrybatch'),
        ),
        migrations.CreateModel(
            name='BirdTransfer',
            fields=[
                ('transfer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transfer_date', models.DateField(db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('capacity_warning_acknowledged', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('REVERSED', 'Reversed')], db_index=True, default='COMPLETED', max_length=12)),
                ('reversal_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bird_transfers_created', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='poultry.birdtransfer')),
                ('source_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bird_transfers_out', to='poultry.poultrybatch')),
            ],
            options={
                'ordering': ['-transfer_date', '-transfer_id'],
            },
        ),
        migrations.CreateModel(
            name='BirdTransferAllocation',
            fields=[
                ('allocation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('projected_house_birds', models.PositiveIntegerField(default=0)),
                ('exceeded_capacity', models.BooleanField(default=False)),
                ('destination_batch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_transfer_allocation', to='poultry.poultrybatch')),
                ('destination_house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bird_transfer_allocations_in', to='poultry.poultryhouse')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='poultry.birdtransfer')),
            ],
            options={
                'ordering': ['allocation_id'],
            },
        ),
        migrations.CreateModel(
            name='HouseBirdMovement',
            fields=[
                ('movement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('occurred_on', models.DateField(db_index=True)),
                ('direction', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=3)),
                ('movement_type', models.CharField(choices=[('OPENING', 'Opening stock'), ('STOCK_IN', 'New stocking'), ('TRANSFER_IN', 'Transfer in'), ('TRANSFER_OUT', 'Transfer out'), ('MORTALITY', 'Approved mortality'), ('SALE', 'Delivered bird sale'), ('LEGACY_CLOSE', 'Legacy closed-batch reconciliation'), ('REVERSAL_IN', 'Reversal in'), ('REVERSAL_OUT', 'Reversal out')], db_index=True, max_length=20)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bird_movements', to='poultry.poultrybatch')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bird_movements', to='poultry.poultryhouse')),
                ('mortality_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bird_movement', to='poultry.mortalityrecord')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bird_movements_created', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='poultry.housebirdmovement')),
                ('sale_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bird_movement', to='sales.saleitem')),
                ('transfer_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='poultry.birdtransferallocation')),
            ],
            options={
                'ordering': ['-occurred_on', '-movement_id'],
            },
        ),
        migrations.AddIndex(
            model_name='birdtransfer',
            index=models.Index(fields=['source_batch', 'transfer_date'], name='poultry_bt_source_date_idx'),
        ),
        migrations.AddIndex(
            model_name='birdtransfer',
            index=models.Index(fields=['status', 'transfer_date'], name='poultry_bt_status_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='birdtransferallocation',
            constraint=models.UniqueConstraint(fields=('transfer', 'destination_house'), name='uniq_transfer_destination_house'),
        ),
        migrations.AddConstraint(
            model_name='birdtransferallocation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='bird_transfer_quantity_positive'),
        ),
        migrations.AddIndex(
            model_name='housebirdmovement',
            index=models.Index(fields=['house', 'occurred_on'], name='poultry_hbm_house_date_idx'),
        ),
        migrations.AddIndex(
            model_name='housebirdmovement',
            index=models.Index(fields=['batch', 'occurred_on'], name='poultry_hbm_batch_date_idx'),
        ),
        migrations.AddIndex(
            model_name='housebirdmovement',
            index=models.Index(fields=['movement_type', 'occurred_on'], name='poultry_hbm_type_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='housebirdmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='house_bird_movement_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='housebirdmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('transfer_allocation__isnull', False)), fields=('transfer_allocation', 'movement_type'), name='uniq_transfer_allocation_movement_type'),
        ),
    ]
