# Generated by Django 5.2.11 on 2026-02-28 03:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poultry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthEvent',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_date', models.DateField(db_index=True)),
                ('event_type', models.CharField(choices=[('TREATMENT', 'Treatment'), ('VACCINATION', 'Vaccination'), ('VET_VISIT', 'Vet Visit'), ('DISEASE', 'Disease/Outbreak'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('symptoms_or_reason', models.TextField(blank=True)),
                ('action_taken', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('administered_by_name', models.CharField(blank=True, max_length=120)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_events', to='poultry.poultrybatch')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_events_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_date', '-event_id'],
            },
        ),
        migrations.CreateModel(
            name='HealthEventItem',
            fields=[
                ('line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=150)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('dosage_note', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='health.healthevent')),
            ],
        ),
        migrations.AddIndex(
            model_name='healthevent',
            index=models.Index(fields=['batch', 'event_date'], name='health_heal_batch_i_d8587d_idx'),
        ),
        migrations.AddIndex(
            model_name='healthevent',
            index=models.Index(fields=['event_type', 'event_date'], name='health_heal_event_t_6dda82_idx'),
        ),
        migrations.AddIndex(
            model_name='healtheventitem',
            index=models.Index(fields=['event'], name='health_heal_event_i_aebc17_idx'),
        ),
    ]
