# Generated by Django 6.0.3 on 2026-05-04 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SicknessReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('house', models.CharField(max_length=10)),
                ('disease', models.CharField(blank=True, max_length=255)),
                ('affected', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='sickness/')),
                ('action', models.CharField(choices=[('sickbay', 'Moved to Sickbay'), ('isolate', 'Isolated'), ('crowd', 'Left in Crowd')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
