# Generated by Django 5.2.11 on 2026-05-04 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_sickness_report_links(apps, schema_editor):
    SicknessReport = apps.get_model("health", "SicknessReport")
    PoultryHouse = apps.get_model("poultry", "PoultryHouse")
    PoultryBatch = apps.get_model("poultry", "PoultryBatch")

    for report in SicknessReport.objects.all():
        raw_house = (report.house or "").strip()
        house = None

        if raw_house:
            if raw_house.isdigit():
                house = PoultryHouse.objects.filter(pk=int(raw_house)).first()
            if house is None:
                house = PoultryHouse.objects.filter(
                    models.Q(house_code__iexact=raw_house) | models.Q(name__iexact=raw_house)
                ).first()

        if house is not None:
            report.house_ref_id = house.pk
            report.house = house.name or house.house_code
            batch = (
                PoultryBatch.objects.filter(house_id=house.pk, status="ACTIVE")
                .order_by("-created_at")
                .first()
            )
            report.batch_id = batch.pk if batch is not None else None

        report.isolated = report.action in {"sickbay", "isolate"}
        if report.isolated:
            house_name = (report.house or "").strip() or "Unassigned House"
            disease_name = (report.disease or "").strip() or "General"
            report.isolation_name = f"{house_name}-Isolation({disease_name})"
        else:
            report.isolation_name = ""

        report.save(update_fields=["house", "house_ref", "batch", "isolated", "isolation_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_sicknessreport'),
        ('poultry', '0007_cleaningphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sicknessreport',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='sicknessreport',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sickness_reports', to='poultry.poultrybatch'),
        ),
        migrations.AddField(
            model_name='sicknessreport',
            name='house_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sickness_reports', to='poultry.poultryhouse'),
        ),
        migrations.AddField(
            model_name='sicknessreport',
            name='isolated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sicknessreport',
            name='isolation_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sicknessreport',
            name='house',
            field=models.CharField(max_length=100),
        ),
        migrations.RunPython(backfill_sickness_report_links, migrations.RunPython.noop),
        migrations.CreateModel(
            name='SickbayCleaningRecord',
            fields=[
                ('cleaning_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('record_date', models.DateField(db_index=True)),
                ('sickbay_cleaned', models.BooleanField(default=False)),
                ('disinfection_done', models.BooleanField(default=False)),
                ('equipment_cleaned', models.BooleanField(default=False)),
                ('water_changed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sickbay_cleaning_records', to=settings.AUTH_USER_MODEL)),
                ('sickness_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sickbay_cleanings', to='health.sicknessreport')),
            ],
            options={
                'ordering': ['-record_date', '-cleaning_id'],
                'indexes': [models.Index(fields=['record_date'], name='health_sick_record__b69c15_idx')],
            },
        ),
    ]
