# Generated by Django 6.0.3 on 2026-05-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_alter_sicknessreport_options_sicknessreport_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sicknessreport',
            name='action',
            field=models.CharField(choices=[('sickbay', 'Moved to Sickbay'), ('crowd', 'Left in Crowd')], max_length=20),
        ),
    ]
