# Generated by Django 5.2.11 on 2026-05-05 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_supervisor_sickness_fields(apps, schema_editor):
    SicknessReport = apps.get_model("health", "SicknessReport")

    for report in SicknessReport.objects.all():
        diagnosis_text = (report.disease or "").strip()
        if diagnosis_text and not (report.symptoms or "").strip():
            report.symptoms = diagnosis_text
        if diagnosis_text and report.case_status == "REPORTED":
            report.case_status = "DIAGNOSED"
        report.save(update_fields=["symptoms", "case_status"])


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_persist_until_resolved'),
        ('health', '0004_alter_sicknessreport_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sicknessreport',
            name='bird_identifier',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sicknessreport',
            name='case_status',
            field=models.CharField(choices=[('REPORTED', 'Awaiting Vet Diagnosis'), ('DIAGNOSED', 'Treatment Planned'), ('TREATMENT_COMPLETED', 'Treatment Given')], db_index=True, default='REPORTED', max_length=30),
        ),
        migrations.AddField(
            model_name='sicknessreport',
            name='diagnosis_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sicknessreport',
            name='symptoms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sicknessreport',
            name='treatment_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sicknessreport',
            name='vet_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sicknessreport',
            name='vet_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sicknessreport',
            name='action',
            field=models.CharField(choices=[('sickbay', 'Moved to Sickbay'), ('isolate', 'Isolated'), ('crowd', 'Left in Crowd')], max_length=20),
        ),
        migrations.RunPython(backfill_supervisor_sickness_fields, migrations.RunPython.noop),
        migrations.CreateModel(
            name='TreatmentPlanItem',
            fields=[
                ('plan_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=150)),
                ('dosage', models.CharField(max_length=120)),
                ('administration_route', models.CharField(blank=True, max_length=80)),
                ('instructions', models.TextField(blank=True)),
                ('scheduled_for', models.DateField(blank=True, db_index=True, null=True)),
                ('is_given', models.BooleanField(db_index=True, default=False)),
                ('given_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_plan_items', to='alerts.alert')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plan_items_created', to=settings.AUTH_USER_MODEL)),
                ('marked_given_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_plan_items_given', to=settings.AUTH_USER_MODEL)),
                ('sickness_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_items', to='health.sicknessreport')),
            ],
            options={
                'ordering': ['is_given', 'scheduled_for', '-created_at'],
                'indexes': [models.Index(fields=['is_given', 'scheduled_for'], name='health_trea_is_give_251678_idx')],
            },
        ),
    ]
