# Generated by Django 6.0.3 on 2026-05-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_normalize_sickbay_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentplanitem',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='frequency_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
