# Generated by Django 6.0.3 on 2026-05-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_treatmentplanitem_duration_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatmentplanitem',
            old_name='frequency_days',
            new_name='frequency_hours',
        ),
        migrations.RemoveField(
            model_name='treatmentplanitem',
            name='start_date',
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentplanitem',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
