# Generated by Django 6.0.3 on 2026-05-08 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_persist_until_resolved'),
        ('health', '0008_rename_frequency_days_treatmentplanitem_frequency_hours_and_more'),
        ('poultry', '0008_cleaningrecord_sickness_report_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('schedule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=150)),
                ('brand', models.CharField(blank=True, max_length=150)),
                ('dosage', models.CharField(blank=True, max_length=120)),
                ('administration_mode', models.CharField(blank=True, max_length=120)),
                ('frequency_days', models.PositiveIntegerField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('vet_name', models.CharField(blank=True, max_length=120)),
                ('brand_expiry_date', models.DateField(blank=True, null=True)),
                ('number_vaccinated', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ADMINISTERED', 'Administered')], db_index=True, default='SCHEDULED', max_length=20)),
                ('administered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations_administered', to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_schedules', to='alerts.alert')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vaccination_schedules', to='poultry.poultrybatch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccination_schedules_created', to=settings.AUTH_USER_MODEL)),
                ('house_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vaccination_schedules', to='poultry.poultryhouse')),
            ],
            options={
                'ordering': ['-scheduled_for', '-created_at'],
                'indexes': [models.Index(fields=['scheduled_for'], name='health_vacc_schedul_4d3547_idx'), models.Index(fields=['status', 'scheduled_for'], name='health_vacc_status_e28df0_idx')],
            },
        ),
    ]
