# Generated by Codex on 2026-05-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0009_vaccinationschedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sicknessreport",
            name="transferred_back_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sicknessreport",
            name="transferred_back_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sickness_cases_transferred_back",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
