# Generated by Django 6.0.3 on 2026-06-19 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Auto-generated code (e.g., SE0034, CRO2875)', max_length=20, unique=True)),
                ('prefix', models.CharField(choices=[('SE', 'Sales - Eggs'), ('SO', 'Sales - Off-Layer'), ('CRO', 'Cost of Revenue'), ('DEP', 'Depreciation'), ('ME', 'Monthly Expenses')], max_length=3)),
                ('account_type', models.CharField(choices=[('REVENUE', 'Revenue'), ('COST_OF_REVENUE', 'Cost of Revenue'), ('DEPRECIATION', 'Depreciation'), ('MONTHLY_EXPENSES', 'Monthly Expenses')], db_index=True, max_length=20)),
                ('account_name', models.CharField(help_text="Product/category name (e.g., 'Eggs', 'Feed', 'Utilities')", max_length=150)),
                ('sequence_number', models.IntegerField(help_text='Sequential number for this prefix (used to generate code)')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Content type of the related transaction (SaleInvoice, ExpenseTransaction, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Accounting Code',
                'verbose_name_plural': 'Accounting Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['prefix', 'account_type'], name='accounting__prefix_61ebce_idx'), models.Index(fields=['account_type', 'created_at'], name='accounting__account_afcaf2_idx')],
            },
        ),
    ]
