# Generated by Django 5.2.11 on 2026-06-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_balance_sheet_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingcode',
            name='account_type',
            field=models.CharField(choices=[('REVENUE', 'Revenue'), ('OTHER_INCOME', 'Other Income'), ('COST_OF_REVENUE', 'Cost of Revenue'), ('DEPRECIATION', 'Depreciation'), ('EXPENSES', 'Expenses'), ('OTHER_EXPENSES', 'Other Expenses'), ('MONTHLY_EXPENSES', 'Monthly Expenses')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='accountingcode',
            name='prefix',
            field=models.CharField(choices=[('SE', 'Sales - Eggs'), ('SO', 'Sales - Off-Layer'), ('OIN', 'Other Income'), ('CRO', 'Cost of Revenue'), ('DEP', 'Depreciation'), ('EXP', 'Expenses'), ('OEX', 'Other Expenses'), ('ME', 'Monthly Expenses')], max_length=3),
        ),
    ]
