# Generated by Django 5.2.11 on 2026-06-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_accountingcode_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheetaccount',
            name='account_type',
            field=models.CharField(choices=[('FIXED_ASSET', 'Fixed Asset'), ('ACCUMULATED_DEPRECIATION', 'Accumulated Depreciation'), ('CURRENT_ASSET', 'Current Asset'), ('RECEIVABLE', 'Receivable'), ('PREPAYMENT', 'Prepayment'), ('BANK_AND_CASH', 'Bank and Cash'), ('NON_CURRENT_LIABILITY', 'Non Current Liability'), ('CURRENT_LIABILITY', 'Current Liability'), ('PAYABLE', 'Payable'), ('EQUITY', 'Equity'), ('CURRENT_YEAR_EARNINGS', 'Current Year Earnings')], db_index=True, max_length=30),
        ),
    ]
