# Generated by Django 5.2.11 on 2026-06-29 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_balancesheetaccount_account_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetConstructionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150)),
                ('asset_category', models.CharField(choices=[('BUILDING', 'Building'), ('LAND', 'Land'), ('SOFTWARE', 'Software'), ('VEHICLE', 'Vehicle'), ('COMPUTER_EQUIPMENT', 'Computer Equipment'), ('HARDWARE_EQUIPMENT', 'Hardware Equipment'), ('OTHER', 'Other')], db_index=True, max_length=40)),
                ('start_date', models.DateField(db_index=True)),
                ('completed_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_construction_projects_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssetConstructionCostLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_date', models.DateField(db_index=True)),
                ('cost_item_name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_construction_cost_lines_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_lines', to='accounting.assetconstructionproject')),
            ],
            options={
                'ordering': ['-cost_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FixedAssetAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=150)),
                ('asset_category', models.CharField(choices=[('BUILDING', 'Building'), ('LAND', 'Land'), ('SOFTWARE', 'Software'), ('VEHICLE', 'Vehicle'), ('COMPUTER_EQUIPMENT', 'Computer Equipment'), ('HARDWARE_EQUIPMENT', 'Hardware Equipment'), ('OTHER', 'Other')], db_index=True, max_length=40)),
                ('acquisition_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_acquisitions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acquisition_date', '-id'],
            },
        ),
    ]
