# Generated by Django 5.2.11 on 2026-06-29 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_assetconstructionproject_assetconstructioncostline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetconstructionproject',
            name='capitalized_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='assetconstructionproject',
            name='capitalized_on',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='assetconstructionproject',
            name='in_service_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='assetconstructionproject',
            name='is_depreciable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assetconstructionproject',
            name='residual_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='assetconstructionproject',
            name='useful_life_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixedassetacquisition',
            name='depreciation_method',
            field=models.CharField(choices=[('STRAIGHT_LINE', 'Straight Line')], default='STRAIGHT_LINE', max_length=30),
        ),
        migrations.AddField(
            model_name='fixedassetacquisition',
            name='in_service_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='fixedassetacquisition',
            name='is_depreciable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fixedassetacquisition',
            name='residual_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='fixedassetacquisition',
            name='source_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capitalized_asset', to='accounting.assetconstructionproject'),
        ),
        migrations.AddField(
            model_name='fixedassetacquisition',
            name='useful_life_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
