# Generated by Django 5.2.11 on 2026-06-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_assetconstructionproject_capitalized_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetconstructionproject',
            name='asset_category',
            field=models.CharField(choices=[('LAND', 'Land'), ('POULTRY_HOUSE', 'Poultry House'), ('BROILER_HOUSE', 'Broiler House'), ('LAYER_HOUSE', 'Layer House'), ('HATCHERY_BUILDING', 'Hatchery Building'), ('FEED_STORE', 'Feed Store / Warehouse'), ('OFFICE_BUILDING', 'Office Building'), ('STAFF_QUARTERS', 'Staff Quarters'), ('SECURITY_BOOTH', 'Security Booth'), ('GENERAL_BUILDING', 'General Building'), ('CAGES_REARING', 'Cages & Rearing Equipment'), ('FEEDERS', 'Feeders'), ('DRINKERS_WATERING', 'Drinkers / Watering Systems'), ('INCUBATORS', 'Incubators & Hatchery Equipment'), ('EGG_HANDLING', 'Egg Handling Equipment'), ('EGG_GRADING', 'Egg Grading & Packing Equipment'), ('VENTILATION', 'Ventilation & Climate Control Systems'), ('LIGHTING', 'Lighting Systems'), ('BIOSECURITY', 'Biosecurity Equipment'), ('WASTE_MANAGEMENT', 'Waste Management Systems'), ('FEED_MIXING', 'Feed Mixing Equipment'), ('FEED_STORAGE', 'Feed Storage Silos / Bins'), ('TRACTOR_MACHINERY', 'Tractor & Farm Machinery'), ('GENERATOR', 'Generator / Electrical Installation'), ('BOREHOLE_WATER', 'Borehole & Water Supply Systems'), ('COLD_STORAGE', 'Cold Storage / Refrigeration'), ('VEHICLE', 'Vehicle (Delivery / Farm)'), ('COMPUTER_EQUIPMENT', 'Computer Equipment'), ('OFFICE_EQUIPMENT', 'Office Equipment'), ('FURNITURE_FITTINGS', 'Furniture & Fittings'), ('SECURITY_SYSTEM', 'Security System (CCTV / Alarm)'), ('SOFTWARE', 'Software'), ('HARDWARE_EQUIPMENT', 'Hardware Equipment'), ('OTHER', 'Other')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='fixedassetacquisition',
            name='asset_category',
            field=models.CharField(choices=[('LAND', 'Land'), ('POULTRY_HOUSE', 'Poultry House'), ('BROILER_HOUSE', 'Broiler House'), ('LAYER_HOUSE', 'Layer House'), ('HATCHERY_BUILDING', 'Hatchery Building'), ('FEED_STORE', 'Feed Store / Warehouse'), ('OFFICE_BUILDING', 'Office Building'), ('STAFF_QUARTERS', 'Staff Quarters'), ('SECURITY_BOOTH', 'Security Booth'), ('GENERAL_BUILDING', 'General Building'), ('CAGES_REARING', 'Cages & Rearing Equipment'), ('FEEDERS', 'Feeders'), ('DRINKERS_WATERING', 'Drinkers / Watering Systems'), ('INCUBATORS', 'Incubators & Hatchery Equipment'), ('EGG_HANDLING', 'Egg Handling Equipment'), ('EGG_GRADING', 'Egg Grading & Packing Equipment'), ('VENTILATION', 'Ventilation & Climate Control Systems'), ('LIGHTING', 'Lighting Systems'), ('BIOSECURITY', 'Biosecurity Equipment'), ('WASTE_MANAGEMENT', 'Waste Management Systems'), ('FEED_MIXING', 'Feed Mixing Equipment'), ('FEED_STORAGE', 'Feed Storage Silos / Bins'), ('TRACTOR_MACHINERY', 'Tractor & Farm Machinery'), ('GENERATOR', 'Generator / Electrical Installation'), ('BOREHOLE_WATER', 'Borehole & Water Supply Systems'), ('COLD_STORAGE', 'Cold Storage / Refrigeration'), ('VEHICLE', 'Vehicle (Delivery / Farm)'), ('COMPUTER_EQUIPMENT', 'Computer Equipment'), ('OFFICE_EQUIPMENT', 'Office Equipment'), ('FURNITURE_FITTINGS', 'Furniture & Fittings'), ('SECURITY_SYSTEM', 'Security System (CCTV / Alarm)'), ('SOFTWARE', 'Software'), ('HARDWARE_EQUIPMENT', 'Hardware Equipment'), ('OTHER', 'Other')], db_index=True, max_length=40),
        ),
    ]
