# Generated by Django 6.0.7 on 2026-07-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_financial_statement_sections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttype',
            options={'ordering': ['report_section__statement__display_order', 'report_section__display_order', 'name']},
        ),
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='accounting__account_35a3f4_idx',
            old_name='accounting_c_account_24bbba_idx',
        ),
    ]
