# Generated by Django 6.0.7 on 2026-07-31 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_supplier_visible_accounts'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='accounting__content_2d5599_idx',
            old_name='accounting_j_content_f04c0f_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='accounting__status_553504_idx',
            old_name='accounting_j_status_86c307_idx',
        ),
        migrations.RenameIndex(
            model_name='journalline',
            new_name='accounting__account_c6b1e8_idx',
            old_name='accounting_j_account_84fe03_idx',
        ),
    ]
