# Generated by Django 5.2.11 on 2026-09-15 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_financial_document_numbers(apps, schema_editor):
    """Give every historic journal an immutable FDN without a race-prone counter."""
    JournalEntry = apps.get_model("accounting", "JournalEntry")
    for entry in JournalEntry.objects.filter(fdn__isnull=True).only("pk", "entry_date").iterator():
        JournalEntry.objects.filter(pk=entry.pk, fdn__isnull=True).update(
            fdn=f"FDN-{entry.entry_date:%Y%m}-{entry.pk:06d}",
        )


def noop_reverse_fdn_backfill(apps, schema_editor):
    # Historic FDNs are accounting evidence. Do not erase them on a migration
    # rollback; the schema rollback itself is not a supported audit operation.
    return


def _next_prefix(AccountType, seed):
    prefix = seed
    suffix = 2
    while AccountType.objects.filter(prefix=prefix).exists():
        prefix = f"{seed}{suffix}"
        suffix += 1
    return prefix


def seed_payroll_accounting_controls(apps, schema_editor):
    """Move staff advances to AR and seed the LST liability on old databases."""
    AccountType = apps.get_model("accounting", "AccountType")
    BalanceSheetAccount = apps.get_model("accounting", "BalanceSheetAccount")
    ChartOfAccount = apps.get_model("accounting", "ChartOfAccount")
    JournalLine = apps.get_model("accounting", "JournalLine")

    receivable_type = AccountType.objects.filter(legacy_code="RECEIVABLE").first()
    if receivable_type is None:
        receivable_type = AccountType.objects.create(
            name="Receivable",
            prefix=_next_prefix(AccountType, "REC"),
            account_nature="ASSET",
            legacy_code="RECEIVABLE",
            is_active=True,
        )
    liability_type = AccountType.objects.filter(legacy_code="CURRENT_LIABILITY").first()
    if liability_type is None:
        liability_type = AccountType.objects.create(
            name="Current Liability",
            prefix=_next_prefix(AccountType, "CL"),
            account_nature="LIABILITY",
            legacy_code="CURRENT_LIABILITY",
            is_active=True,
        )

    BalanceSheetAccount.objects.update_or_create(
        code="331003",
        defaults={
            "account_name": "Staff Advances Receivable",
            "group": "ASSETS",
            "account_type": "RECEIVABLE",
            "allow_reconciliation": True,
            "is_active": True,
        },
    )
    BalanceSheetAccount.objects.update_or_create(
        code="421017",
        defaults={
            "account_name": "Local Service Tax Payable",
            "group": "LIABILITIES",
            "account_type": "CURRENT_LIABILITY",
            "allow_reconciliation": True,
            "is_active": True,
        },
    )

    # Preserve the previous internal code for integrations while moving its
    # visible ledger to the chart's established receivable code.
    legacy_advance = ChartOfAccount.objects.filter(system_code="PAYROLL_PREPAID_SALARIES").first()
    target_advance = ChartOfAccount.objects.filter(code="331003").first()
    if legacy_advance is not None and target_advance is None:
        # Reuse the legacy account itself so every historic advance journal
        # remains attached to the one receivable ledger.
        target_advance = legacy_advance
        target_advance.code = "331003"
    elif legacy_advance is not None and legacy_advance.pk != target_advance.pk:
        # A genuine 331003 receivable already exists. Consolidate only the
        # former payroll-controlled account's journal lines into it, then
        # release the old compatibility code. This avoids split balances.
        JournalLine.objects.filter(account_id=legacy_advance.pk).update(account_id=target_advance.pk)
        legacy_advance.system_code = None
        legacy_advance.save(update_fields=["system_code"])

    if target_advance is None:
        target_advance = ChartOfAccount.objects.create(
            code="331003",
            system_code="PAYROLL_PREPAID_SALARIES",
            account_name="Staff Advances Receivable",
            account_type=receivable_type,
            allow_reconciliation=True,
            is_active=True,
            description="Salary advances disbursed to staff and recoverable from later salary payments.",
        )
    else:
        target_advance.system_code = "PAYROLL_PREPAID_SALARIES"
        target_advance.account_name = "Staff Advances Receivable"
        target_advance.account_type = receivable_type
        target_advance.allow_reconciliation = True
        target_advance.is_active = True
        target_advance.description = "Salary advances disbursed to staff and recoverable from later salary payments."
        target_advance.save()

    lst_account, _ = ChartOfAccount.objects.get_or_create(
        code="421017",
        defaults={
            "system_code": "PAYROLL_LST_PAYABLE",
            "account_name": "Local Service Tax Payable",
            "account_type": liability_type,
            "allow_reconciliation": True,
            "description": "Local Service Tax withheld from employees and payable to the local authority.",
            "is_active": True,
        },
    )
    if lst_account.system_code != "PAYROLL_LST_PAYABLE":
        lst_account.system_code = "PAYROLL_LST_PAYABLE"
        lst_account.account_name = "Local Service Tax Payable"
        lst_account.account_type = liability_type
        lst_account.allow_reconciliation = True
        lst_account.is_active = True
        lst_account.save()


def unseed_payroll_accounting_controls(apps, schema_editor):
    # Do not remove accounts or change their names on reverse: they may already
    # contain journal history by the time a schema rollback is considered.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_rename_accounting_j_content_f04c0f_idx_accounting__content_2d5599_idx_and_more'),
        ('inventory', '0015_unique_supplier_product_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedassetacquisition',
            name='payment_method_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_acquisitions', to='accounting.paymentmethod'),
        ),
        migrations.AddField(
            model_name='fixedassetacquisition',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Optional supplier selected for this asset acquisition.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_acquisitions', to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='fdn',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='System-generated Financial Document Number. It is immutable once assigned.', max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversal_of',
            field=models.OneToOneField(blank=True, help_text='The posted entry this entry reverses. Reversals are never edited in place.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_entry', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='void_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries_voided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fixedassetacquisition',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOID', 'Void')], db_index=True, default='POSTED', max_length=20),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('fiscal_year', models.PositiveIntegerField(db_index=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked')], db_index=True, default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fiscal_year', '-version', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('COMPLETE', 'Complete'), ('COMPLETE_WITH_ERRORS', 'Complete with errors')], default='COMPLETE', max_length=30)),
                ('posted_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('error_summary', models.TextField(blank=True)),
                ('ran_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.PositiveIntegerField(db_index=True)),
                ('period_number', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('is_closed', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['fiscal_year', 'period_number'],
                'constraints': [models.UniqueConstraint(fields=('fiscal_year', 'period_number'), name='unique_fiscal_year_period')],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='accounting.chartofaccount')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.budget')),
                ('fiscal_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='accounting.fiscalperiod')),
            ],
            options={
                'ordering': ['fiscal_period__fiscal_year', 'fiscal_period__period_number', 'account__code'],
            },
        ),
        migrations.CreateModel(
            name='FixedAssetDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_date', models.DateField(db_index=True)),
                ('proceeds', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField()),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('book_value', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('gain_loss', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disposal', to='accounting.fixedassetacquisition')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_disposals_created', to=settings.AUTH_USER_MODEL)),
                ('depreciation_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_disposal_depreciation', to='accounting.journalentry')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_disposal_journal', to='accounting.journalentry')),
                ('payment_method_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_disposals', to='accounting.paymentmethod')),
            ],
            options={
                'ordering': ['-disposal_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FixedAssetRevaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revaluation_date', models.DateField(db_index=True)),
                ('old_book_value', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('new_value', models.DecimalField(decimal_places=2, help_text='New carrying value after revaluation.', max_digits=14)),
                ('adjustment', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revaluations', to='accounting.fixedassetacquisition')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_revaluations_created', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_revaluation_journal', to='accounting.journalentry')),
            ],
            options={
                'ordering': ['-revaluation_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('fiscal_year', 'version'), name='unique_budget_version_per_year'),
        ),
        migrations.AddConstraint(
            model_name='depreciationrun',
            constraint=models.UniqueConstraint(fields=('period_year', 'period_month'), name='unique_depreciation_run_period'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.UniqueConstraint(fields=('budget', 'account', 'fiscal_period'), name='unique_budget_account_period'),
        ),
        migrations.AddConstraint(
            model_name='fixedassetrevaluation',
            constraint=models.UniqueConstraint(fields=('asset', 'revaluation_date'), name='unique_asset_revaluation_date'),
        ),
        migrations.RunPython(backfill_financial_document_numbers, noop_reverse_fdn_backfill),
        migrations.RunPython(seed_payroll_accounting_controls, unseed_payroll_accounting_controls),
    ]
