# Generated by Django 5.2.11 on 2026-02-27 22:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poultry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('allow_credit', models.BooleanField(default=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credit_days', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SaleInvoice',
            fields=[
                ('invoice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(db_index=True, max_length=60, unique=True)),
                ('invoice_date', models.DateField(db_index=True)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='sales.customer')),
            ],
            options={
                'ordering': ['-invoice_date', '-invoice_id'],
            },
        ),
        migrations.CreateModel(
            name='ReceivableLedger',
            fields=[
                ('receivable_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receivable', to='sales.saleinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField(db_index=True)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('MOMO', 'Mobile Money'), ('BANK', 'Bank'), ('OTHER', 'Other')], default='CASH', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.customer')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_payments_received', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.saleinvoice')),
            ],
            options={
                'ordering': ['-payment_date', '-payment_id'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=120)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('unit', models.CharField(default='trays', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='poultry.poultrybatch')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.saleinvoice')),
            ],
        ),
        migrations.AddIndex(
            model_name='saleinvoice',
            index=models.Index(fields=['customer', 'invoice_date'], name='sales_salei_custome_179e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='saleinvoice',
            index=models.Index(fields=['status', 'invoice_date'], name='sales_salei_status_29b138_idx'),
        ),
        migrations.AddIndex(
            model_name='receivableledger',
            index=models.Index(fields=['balance'], name='sales_recei_balance_49e917_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['customer', 'payment_date'], name='sales_custo_custome_33b9b5_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['invoice', 'payment_date'], name='sales_custo_invoice_a5c0b7_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['batch'], name='sales_salei_batch_i_810781_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['invoice'], name='sales_salei_invoice_79d050_idx'),
        ),
    ]
