# Generated by Django 5.2.11 on 2026-09-15 03:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_receivable_history(apps, schema_editor):
    """Give existing customer balances a readable opening audit trail."""
    ReceivableLedger = apps.get_model("sales", "ReceivableLedger")
    ReceivableEntry = apps.get_model("sales", "ReceivableEntry")
    CustomerPayment = apps.get_model("sales", "CustomerPayment")
    db_alias = schema_editor.connection.alias
    zero = Decimal("0.00")

    for ledger in ReceivableLedger.objects.using(db_alias).select_related("invoice").iterator():
        invoice = ledger.invoice
        amount_due = ledger.amount_due or zero
        if amount_due <= zero:
            continue

        ReceivableEntry.objects.using(db_alias).create(
            receivable_id=ledger.pk,
            entry_date=invoice.invoice_date,
            entry_type="INVOICE",
            amount=amount_due,
            balance_after=amount_due,
            reference=invoice.invoice_no,
            notes="Opening receivable history created during upgrade.",
        )

        running_paid = zero
        for payment in CustomerPayment.objects.using(db_alias).filter(
            invoice_id=ledger.invoice_id
        ).order_by("payment_date", "payment_id"):
            payment_amount = payment.amount or zero
            if payment_amount <= zero:
                continue
            running_paid += payment_amount
            balance_after = max(amount_due - running_paid, zero)
            ReceivableEntry.objects.using(db_alias).create(
                receivable_id=ledger.pk,
                entry_date=payment.payment_date,
                entry_type="PAYMENT",
                amount=payment_amount,
                balance_after=balance_after,
                reference=payment.reference or f"PAY-{payment.payment_id}",
                notes="Historical payment imported during upgrade.",
                created_by_id=payment.received_by_id,
            )

        # Some older data has only the aggregate balance fields, with no
        # individual CustomerPayment rows. Preserve the known amount as one
        # clearly-labelled opening movement rather than silently hiding it.
        aggregate_paid = ledger.amount_paid or zero
        if aggregate_paid > running_paid:
            inferred_amount = aggregate_paid - running_paid
            ReceivableEntry.objects.using(db_alias).create(
                receivable_id=ledger.pk,
                entry_date=ledger.last_payment_date or invoice.invoice_date,
                entry_type="PAYMENT",
                amount=inferred_amount,
                balance_after=max(amount_due - aggregate_paid, zero),
                reference="OPENING-BALANCE",
                notes="Historical aggregate payment imported during upgrade.",
            )


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_saleitem_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivableEntry',
            fields=[
                ('receivable_entry_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateField(db_index=True)),
                ('entry_type', models.CharField(choices=[('INVOICE', 'Invoice charge'), ('PAYMENT', 'Customer payment'), ('ADJUSTMENT', 'Approved adjustment')], db_index=True, max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivable_entries_created', to=settings.AUTH_USER_MODEL)),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='sales.receivableledger')),
            ],
            options={
                'ordering': ['-entry_date', '-receivable_entry_id'],
                'indexes': [models.Index(fields=['receivable', 'entry_date'], name='sales_recei_receiva_2a96a4_idx'), models.Index(fields=['entry_type', 'entry_date'], name='sales_recei_entry_t_c39fff_idx')],
            },
        ),
        migrations.RunPython(backfill_receivable_history, migrations.RunPython.noop),
    ]
