# Generated by Django 6.1 on 2026-09-28 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_receivable_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='sales.customer'),
        ),
    ]
