# Generated by Django 6.1 on 2026-09-28 12:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_saleinvoice_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='change_given',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
